'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const LBM=require('./engine.js');
const {dirs,opposite,weights}=LBM;
function near(a,b,tol=1e-10,message=''){assert.ok(Math.abs(a-b)<=tol,`${message}: ${a} vs ${b}`);}
function sum(a){return a.reduce((s,v)=>s+v,0);}
function moments(a,b){let r=0,x=0,y=0;for(let i=0;i<9;i++){r+=a[b+i];x+=a[b+i]*dirs[i][0];y+=a[b+i]*dirs[i][1];}return[r,x,y];}
const nx=12,ny=8,mask=new Uint8Array(nx*ny);mask[4*nx+4]=1;
const e=LBM.make(nx,ny,{solid:mask,seed:42}),p=e.prepare();
assert.equal(e.prepare(),p,'prepare must return same pending step');
// Independently generated by NumPy RandomState(42) using the upstream formula.
const numpyFirst=[8.785153536829311,8.729645421369161,8.798351313137898,29.855028385142337,8.721263055430537,8.721264490628373,8.879782670066065,8.808819204379024,8.700691923017308];
for(let i=0;i<9;i++)near(p.start[i],numpyFirst[i],1e-12,'NumPy seed42 normalized population');
for(let y=0;y<ny;y++)for(let x=0;x<nx;x++)for(let i=0;i<9;i++){
  const dst=(((y+dirs[i][1]+ny)%ny)*nx+(x+dirs[i][0]+nx)%nx)*9+i;
  assert.equal(p.streamed[dst],p.start[(y*nx+x)*9+i],'push direction / periodic edge');
}
near(sum(p.start),sum(p.streamed),1e-8,'stream conserves global mass');
for(let node=0;node<nx*ny;node++) {
  const a=moments(p.streamed,node*9),b=moments(p.collided,node*9);
  for(let m=0;m<3;m++)near(a[m],b[m],2e-12,'BGK conserves local mass and momentum');
  for(let i=0;i<9;i++)assert.equal(p.bounced[node*9+i],mask[node]?p.streamed[node*9+opposite[i]]:p.collided[node*9+i]);
}
near(sum(p.start),sum(p.bounced),1e-8,'complete update conserves mass');
const oldN=e.n;e.commit();assert.equal(e.n,oldN+1);assert.equal(e.F,p.bounced);
const q=e.prepare(),solidNode=4*nx+4;
// The reflected value is held at the solid node after bounce; it does not
// appear in a fluid neighbour until the following push-stream operation.
for(let i=1;i<9;i++) {
  const dest=(((4+dirs[i][1]+ny)%ny)*nx+(4+dirs[i][0]+nx)%nx)*9+i;
  assert.equal(p.bounced[solidNode*9+i],p.streamed[solidNode*9+opposite[i]],'bounce stores reversed value inside solid node');
  assert.equal(q.streamed[dest],p.bounced[solidNode*9+i],'stored bounce releases next streaming to one neighbour');
}
// Equilibrium is invariant without an obstacle. It also checks physical uy.
const uniform=new Float64Array(nx*ny*9),u=.05,v=.03;
for(let node=0;node<nx*ny;node++)for(let i=0;i<9;i++){
  const cu=dirs[i][0]*u-dirs[i][1]*v;
  uniform[node*9+i]=100*weights[i]*(1+3*cu+4.5*cu*cu-1.5*(u*u+v*v));
}
const equilibrium=LBM.make(nx,ny,{solid:new Uint8Array(nx*ny),initial:uniform});equilibrium.advance(10);
for(let k=0;k<uniform.length;k++)near(equilibrium.F[k],uniform[k],1e-12,'uniform equilibrium');
const m=equilibrium.macros();near(m.ux[0],u);near(m.uy[0],v);near(m.vorticity[0],0);
// Independent affine velocity field checks the physical curl sign,
// canvas-to-physical y conversion, and the centered difference 1/2 factor.
const affine=new Float64Array(nx*ny*9);
for(let y=0;y<ny;y++)for(let x=0;x<nx;x++)for(let i=0;i<9;i++){
  const ax=.002*y,ay=.003*x,cu=dirs[i][0]*ax-dirs[i][1]*ay;
  affine[(y*nx+x)*9+i]=100*weights[i]*(1+3*cu+4.5*cu*cu-1.5*(ax*ax+ay*ay));
}
near(equilibrium.macros(affine).vorticity[2*nx+2],.005,1e-14,'physical vorticity');
const withSolid=e.macros();near(withSolid.ux[solidNode],0);near(withSolid.uy[solidNode],0);assert.ok(Number.isNaN(withSolid.vorticity[solidNode]));
const original=fs.readFileSync(path.join(__dirname,'original-fragment.html'),'utf8');
const match=original.match(/<script[^>]*id="lbm-v6-snapshots"[^>]*>([\s\S]*?)<\/script>/);
assert.ok(match,'original snapshot JSON found');const d=JSON.parse(match[1]);
const lesson=LBM.make(d.nx,d.ny,{solid:d.solid,initial:d.stages[0],n:d.n}),actual=lesson.prepare();
let maxError=0;
for(const [j,key]of [[0,'start'],[1,'streamed'],[2,'collided'],[3,'bounced']])for(let k=0;k<actual[key].length;k++){
 const error=Math.abs(actual[key][k]-d.stages[j][k]);maxError=Math.max(error,maxError);assert.ok(error<3e-5,`${key} reference snapshot ${k}: error ${error}`);
}
const initialMass=sum(lesson.F);lesson.advance(1000);
assert.ok(lesson.F.every(Number.isFinite),'1000 teaching steps finite');near(sum(lesson.F),initialMass,2e-6,'1000 steps conserve total mass');
const flow=LBM.make(240,80,{seed:42}),flowMass=sum(flow.F);const began=Date.now();flow.advance(1000);
assert.ok(flow.F.every(Number.isFinite),'1000 high-resolution steps finite');near(sum(flow.F),flowMass,3e-5,'1000 high-resolution steps conserve mass');
console.log(JSON.stringify({passed:true,checks:['NumPy seeded initialization','periodic push streaming','BGK mass and momentum','saved solid reversal','next-stream release','equilibrium and physical uy','physical vorticity and solid mask','four original snapshots','1000 teaching steps','1000 flow steps'],maxOriginalSnapshotError:maxError,flow1000Milliseconds:Date.now()-began},null,2));
